// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function isValidHttpUrl(url: unknown): url is string {
  if (typeof url !== "string") return false;
  const trimmed = url.trim();
  if (
    !trimmed ||
    trimmed === "undefined" ||
    trimmed === "null" ||
    trimmed === "YOUR_SUPABASE_URL"
  ) {
    return false;
  }
  if (!/^https?:\/\//i.test(trimmed)) return false;
  try {
    const parsed = new URL(trimmed);
    return parsed.protocol === "http:" || parsed.protocol === "https:";
  } catch {
    return false;
  }
}

function getValidSupabaseAdminUrl(): string {
  const envProcess = typeof process !== "undefined" ? process.env?.["SUPABASE_URL"] : undefined;
  if (isValidHttpUrl(envProcess)) return envProcess.trim();

  const envProcessVite =
    typeof process !== "undefined" ? process.env?.["VITE_SUPABASE_URL"] : undefined;
  if (isValidHttpUrl(envProcessVite)) return envProcessVite.trim();

  return "https://placeholder-project.supabase.co";
}

function getValidSupabaseServiceRoleKey(): string {
  const candidates = [
    typeof process !== "undefined" ? process.env?.["SUPABASE_SERVICE_ROLE_KEY"] : undefined,
    typeof process !== "undefined" ? process.env?.["SUPABASE_SECRET_KEY"] : undefined,
  ];
  for (const c of candidates) {
    if (typeof c === "string" && c.trim() && c.trim() !== "undefined" && c.trim() !== "null") {
      return c.trim();
    }
  }
  return "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsYWNlaG9sZGVyIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTYwMDAwMDAwMCwiZXhwIjoxOTAwMDAwMDAwfQ.placeholder";
}

function createSupabaseAdminClient() {
  const SUPABASE_URL = getValidSupabaseAdminUrl();
  const SUPABASE_SERVICE_ROLE_KEY = getValidSupabaseServiceRoleKey();

  const isConfigured = Boolean(
    isValidHttpUrl(typeof process !== "undefined" ? process.env?.["SUPABASE_URL"] : undefined) &&
    process.env?.["SUPABASE_SERVICE_ROLE_KEY"],
  );
  if (!isConfigured) {
    console.warn("[Supabase] Missing Supabase server environment variable(s). Using mock client.");
  }

  try {
    return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
      global: {
        fetch: createSupabaseFetch(SUPABASE_SERVICE_ROLE_KEY),
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });
  } catch (err) {
    console.warn("[Supabase] Failed to initialize admin client, falling back to placeholder:", err);
    return createClient<Database>(
      "https://placeholder-project.supabase.co",
      SUPABASE_SERVICE_ROLE_KEY,
      {
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      },
    );
  }
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
